### PR TITLE
[WIP] Update snippets based on time

### PR DESCRIPTION
**Pull request by zanedb**
The site now has three modes, signup, after signup, and after event.

Signup:
image

After signup:
image

After event:
image

Times are obtained via [Moment.js](https://momentjs.com/) and will be automatically changed when the times occur. Therefore, no more deploys of the site are required after the event; it automatically links to DevPost.

### CODE REVIEW

**Comment by itsmingjie** [comment]
Not able to review rn but please make sure my button is not broken after submission :)

**Comment by zanedb** [comment]
I think it still works! Check it out for yourself: https://deploy-preview-12--hackchicago.netlify.com/

**Comment by zanedb** [comment]
Much work is needed before it can be merged. I need to make it compatible with the cookie system introduced in #20 as well.

**Comment by itsmingjie** [comment]
This is definitely going to rage crash... Needs some rework.

**Comment by zanedb** [comment]
Yup, will be worked on soon.

**Comment by zanedb** [comment]
Gonna close this because it's 154 commits behind master & it uses a personal branch. Will re-open PR in a few on new branch with updated code.

**Pull request closed without merging**
